### ISSUE TITLE
While delete filter there is rcmail.confirm_dialog is not a function

### ISSUE THREAD

**Issue by kamilko** [w2c/ispconfig3_roundcube#84]
More from console:
```
Uncaught TypeError: rcmail.confirm_dialog is not a function
    at Object.plugin.ispconfig3_filter.del (filter.js?s=1540295179:15)
    at rcube_webmail.command (app.min.js?s=1493708070:1)
    at HTMLAnchorElement.onclick (?_task=settings&_action=plugin.ispconfig3_filter&_framed=1:108)
```

There was some regression about this error, because as I can check version from commit 274dadc works ok.

**Comment by Churro** [comment]
Thanks for reporting! Indeed, this was a mistake. The function `rcmail.confirm_dialog` is not available in Roundcube <= 1.4 and this can lead to the error message you are describing.

I have now pushed a small code snippet that provides a compatibility shim for `rcmail.confirm_dialog`. In case this function is undefined, a workaround using the native `confirm` function comes into effect.
